### HYPERPARAMETER TUNING FILE ###
# This is the central repository of hyperparameters used in model tuning

GAMMA = 0.99
TRAIN_EPSILON = 0.00
TEST_EPSILON = 0.20
LEARNING_RATE = 0.001

TIMEOUT_STATES = 10000
MAX_ARMIES = 12
INITIAL_PLACEMENT_ARMIES = 120
MIN_ARMIES_PER_TURN = 3
ARMIES_PER_TERRITORY = 0.33333

USEFUL_LIFE = 1000
VALIDATION_GAMES = 10
MODEL_INSTANCE = '0-19'